//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long IdProduct { get; set; }
        public long IdUser { get; set; }
        public string Comment1 { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
